# 20260730b — 局内 HUD 改造（血量 PK 条 / 投降按钮）＋ 训龟大师技能审核 ＋ 地图提升

状态：**待拍板**（§5 有 9 个未决点，其中 U1 U2 U5 必须先定才能动手）

---

## 1. 需求原文（用户 2026-07-30 逐字）

> 新需求
> 1. 对局内的顶部左右新加一个双方血条的pk，表示双方总血量实时变化，需要详细设计下
> 2. 战斗日志按钮移除掉，暂停按钮移除掉，局内不再有退出去或暂停的按钮了，新增投降按钮，点击后有确认认输的提示框。需要设计一下
> 3. 训龟大师的每一个技能效果和特效需要审核一边
> 4. 地图再度需要提升，思考办法
>
> 等确认没问题就搞新的方案书

> ★「需要详细设计下」（需求1）与「需要设计一下」（需求2）＝ 用户明确要求**先出设计再实现**。
> 所以本方案书对这两条给出具体版式与交互，并把不能替用户决定的部分放进 §5 未决点。

---

## 2. 调查结论（现状 + 行号证据）

### 2.1 局内顶栏现在有什么

分辨率 `1280×720`，`canvas_items` + `expand`（[project.godot:41-44](../../project.godot#L41-L44)）。

| 元素 | 位置/尺寸 | 证据 |
|---|---|---|
| 标题文字 | `(24, 16)` | [battle_hud.gd:38](../../scripts/scenes/battle/battle_hud.gd#L38) |
| 双路进度 HUD | `(340, 44)` `700×24` | [battle_hud.gd:44](../../scripts/scenes/battle/battle_hud.gd#L44) |
| 📊 统计按钮 | `(1088, 12)` `52×38` | [battle_hud.gd:72-77](../../scripts/scenes/battle/battle_hud.gd#L72-L77) |
| 📜 日志按钮 | `(1148, 12)` `52×38` | [battle_hud.gd:63-68](../../scripts/scenes/battle/battle_hud.gd#L63-L68) |
| ⏸ 暂停按钮 | `(1208, 12)` `52×38` | [battle_hud.gd:52-59](../../scripts/scenes/battle/battle_hud.gd#L52-L59) |

**顶部左右两侧目前是空的** —— 左边 `x 0..340`（除标题占 24..~200）、右边 `x 1040..1088` 空着，
`1088..1260` 被三个按钮占。需求 2 移除两个按钮后，右侧 `1148..1260` 也会空出来。

**左右队头像框栏不在顶部** —— 它们是**屏幕左右边缘竖直居中**的竖栏
（`PRESET_CENTER_LEFT` 偏移 `(10,0)` / `PRESET_CENTER_RIGHT` 偏移 `(-10,0)`，
[info_panel.gd:15-22](../../scripts/scenes/battle/info_panel.gd#L15-L22)），
每框 `124` 宽、含头像 44×44 + 名字 + 等级牌 + 迷你血条
（[battle_hud.gd:573-640](../../scripts/scenes/battle/battle_hud.gd#L573-L640)）。
**所以"顶部左右"是真的空白区，不会和头像栏打架。**

### 2.2 单位有哪几类（决定"总血量"怎么算）

`battle_spawn.gd` 建单位时打三个互斥标记（[battle_spawn.gd:231-233](../../scripts/scenes/battle/battle_spawn.gd#L231-L233)）：

| 标记 | 是什么 | 血量量级 | 证据 |
|---|---|---|---|
| `minion` | 深海小将（前排 850 / 后排 770） | 中 | [battle_spawn.gd:237](../../scripts/scenes/battle/battle_spawn.gd#L237)、[phase2_minion.gd](../../scripts/gamedata/phase2_minion.gd) |
| `trainer` | 训龟大师（500 血 / 1 攻 / 站着不动） | 中 | [battle_spawn.gd:253](../../scripts/scenes/battle/battle_spawn.gd#L253) |
| `egg` | 龟蛋（纯血包·atk/def/mr 全 0·不动不攻击·免控免斩） | **大** | [battle_spawn.gd:265](../../scripts/scenes/battle/battle_spawn.gd#L265) |
| （无标记） | 28 龟本体 | 中 | [battle_spawn.gd:344](../../scripts/scenes/battle/battle_spawn.gd#L344) |

★**龟蛋是纯血包**，血条把它算进去会把 PK 条变成"蛋血条"，龟死光了条还是满的。这是 U1。

### 2.3 暂停 / 日志现在挂了多少东西

- `_toggle_pause()`（[RealtimeBattle3DScene.gd:1173-1186](../../scripts/scenes/RealtimeBattle3DScene.gd#L1173-L1186)）：
  切 `get_tree().paused`，显隐 `_pause_panel`，并**清拖动/捏合脏态**（暂停发生在拖动中途时 release 收不到）。
- `_pause_panel` 里有三个按钮：`▶ 继续` / `⚔ 重开` / `🏠 返回菜单`
  （[RealtimeBattle3DScene.gd:1155-1163](../../scripts/scenes/RealtimeBattle3DScene.gd#L1155-L1163)）。
  ★**"退出去"目前只有这一条路** —— 需求 2 说"局内不再有退出去的按钮"，所以这三个按钮连着面板一起消失。
- `_CamInputRelay`（[RealtimeBattle3DScene.gd:1164-1170](../../scripts/scenes/RealtimeBattle3DScene.gd#L1164-L1170)）：
  **只为暂停而存在** —— 暂停时根节点 `PAUSABLE` 收不到 `_unhandled_input`，
  所以挂了个 `PROCESS_MODE_ALWAYS` 中继让暂停中仍能拖镜头
  （测试人员 2026-07-22:「点暂停键鼠标似乎也无法拖动」）。暂停没了它就是死代码。
- 结算时会 `_pause_btn.disabled = true`（[battle_hud.gd:194-200](../../scripts/scenes/battle/battle_hud.gd#L194-L200)）。
- 日志：`_toggle_log()` + `_log_panel`（`(24,300)` `440×380`）+ `_log(bbcode)` 追加 + `_LOG_CAP` 封顶
  （[battle_hud.gd:86-112](../../scripts/scenes/battle/battle_hud.gd#L86-L112)、[RealtimeBattle3DScene.gd:1189+](../../scripts/scenes/RealtimeBattle3DScene.gd#L1189)）。

**六个门禁文件提到 pause/log**，其中三条会**直接打红**：

| 门禁 | 断言 | 会不会红 |
|---|---|---|
| [verify_battle_ui.gd:49](../../tests/verify_battle_ui.gd#L49) | `_ok("暂停按钮已建", scene._pause_btn != null)` | **红** |
| [verify_battle_ui.gd:108](../../tests/verify_battle_ui.gd#L108) | `_ok("结算后暂停按钮被禁", ...disabled == true)` | **红** |
| [verify_ios_ui.gd:282](../../tests/verify_ios_ui.gd#L282) | `_ok("暂停按钮已建", bt._pause_btn != null)` | **红** |
| [verify_battle_ui.gd:63+](../../tests/verify_battle_ui.gd#L63) | B 组：`_log` 追加 + 封顶 + `_toggle_log` 显隐 | 看 U3（保留日志系统就不红） |
| `verify_cursor_pause` | 查的是 `get_tree().paused` 下自绘光标跟手，**不查按钮** | 不红（但暂停路径没了它就成了空检查 → 见 U4） |
| `verify_cam_pan` / `verify_interaction_matrix` / `verify_debug_arena` | 提到 pause 但需确认是否断言按钮 | **未验** |

### 2.4 训龟大师有六个主动技

注册表 [RealtimeBattle3DScene.gd:347-357](../../scripts/scenes/RealtimeBattle3DScene.gd#L347-L357)：

| id | 名 | CD | 射程 | 瞄准 |
|---|---|---|---|---|
| `hook` | 钩锁 | 20s | 600 | dir 方向 |
| `fury_potion` | 怒火药水 | 16s | 700 | point 落点 |
| `whistle` | 口哨 | 14s | — | none |
| `glacier` | 冰川 | 17s | 500 | dir 方向 |
| `hunt_order` | 猎龟令 | 30s | 600 | target 锁头 |
| `tame` | 驯服 | 60s | 600 | target 锁头 |

文案在 [TrainerConfigScene.gd:11-17](../../scripts/scenes/TrainerConfigScene.gd#L11-L17) 的 `SKILLS` 数组 `desc` 字段。
已有门禁 `verify_trainer_desc` **把每条 desc 里的每个数字都从代码常量推导出来再回字符串里找**
（[verify_trainer_desc.gd:1-20](../../tests/verify_trainer_desc.gd#L1-L20)）—— 这是「①文案数值 vs 代码」方向。

★**缺的是方向②**：代码里有的效果，文案有没有提。今天刚给 28 龟建了双向审计
（`tools/pet_number_audit.py`），但它**只覆盖龟** —— `__trainer__` 不是龟 id，
`tri_audit` 就把它作为差异 B 报出来（"BASIC_ATK 有 `__trainer__` 但不是龟 id"）。
无头·灵魂打击那次（文案 0.9A 物理 / 代码 0.5A 魔法，且镰刀横扫整段没写）**正是方向②漏掉的形态**，
大师这边现在同样没有方向②的防线。

### 2.5 地图现在是什么

数据驱动：[RealtimeBattle3DScene.gd:920-928](../../scripts/scenes/RealtimeBattle3DScene.gd#L920-L928) 读
`res://data/maps/arena.json`，读不到才退回程序化生成
（[battle_world_builder.gd:84-118](../../scripts/scenes/battle/battle_world_builder.gd#L84-L118)）。

`data/maps/arena.json` 实测：
- `tile = 76.8px`，网格 **29 × 17**（＝ 493 格）
- `types = ["grass","water","stone","sand","void"]`，五种；实际用量 `grass 149 / water 135 / stone 86 / sand 83 / void 40`
- `height` 取值只有 **4 档**：`-0.3 / -0.05 / 0.0 / 0.25`

**关键事实：tile 是纯色方块，没有贴图。** `_tilemap_add()` 收的是一个 `Color`
（程序化分支里三行 `Color(0.10,0.14,0.26)` / `Color(0.12,0.72,0.78)` / `Color(0.24,0.26,0.38)`，
[battle_world_builder.gd:116-118](../../scripts/scenes/battle/battle_world_builder.gd#L116-L118)）。
所以地面的"材质感"目前**完全来自纯色 + 高低差投影**，没有任何像素纹理。

已经有的（别重做）：
- **边框装饰带**：11 种海底装饰，带宽 200px、步长 120、概率 0.30、最小间距 70、随机镜像 + 明暗抖动
  （[battle_world_builder.gd:120-157](../../scripts/scenes/battle/battle_world_builder.gd#L120-L157)。
  ★2026-07-23 已因"太密 + 很多相同装饰"调稀过一轮，**别再往密的方向改**）
- **远景三层**：渐变水幕 / 远礁剪影（程序生成山脊贴图，不用美术图——前景尺度的礁石拉远读不出距离）/ 水面光柱
  （[battle_world_builder.gd:400-534](../../scripts/scenes/battle/battle_world_builder.gd#L400-L534)）
- **远景鱼群 / 气泡柱 / 氛围辉光粒子**（`:581` `:629` `:159`）
- **地图编辑器**：`MAPEDIT=1`，能刷格子和高度并存回 arena.json
- 素材：`assets/sprites/map/` 下 11 个装饰 + `base_dome` + `egg_crack`

**所以"地图还能提升"的真空区是：地面本身（纯色无纹理）、中景（远景和边框之间什么都没有）、
以及"只有一张图"（arena.json 单文件、没有轮换）。** 详见 §4.4。

---

## 3. 需求 ↔ 代码的出入

| # | 需求里的说法 | 代码事实 | 影响 |
|---|---|---|---|
| a | 「顶部左右新加」 | 顶部左右确实空着；但**左右队头像框在屏幕左右边缘竖直居中**，不在顶部 | 无冲突，可以直接放。但"左右"是指**两条分列的条**还是**一条从中间劈开的条**没说清 → **U2** |
| b | 「双方总血量」 | 一方的单位含 **龟 + 小将 + 大师 + 龟蛋** 四类；龟蛋是纯血包（atk/def/mr=0） | 算进蛋会让条失真 → **U1** |
| c | 「局内不再有退出去或暂停的按钮」 | "退出去"目前**只存在于暂停面板里**（`🏠 返回菜单`/`⚔ 重开`）；移除暂停按钮就顺带把唯一的退出路径删掉了 | 需求自洽，但要确认玩家**卡死时**的逃生口只剩投降 → **U5** |
| d | 「战斗日志按钮移除掉」 | 日志是**按钮 + 面板 + `_log()` 记账系统**三件套；`_log()` 被战斗各处调用，且 `verify_battle_ui` B 组守着 | 只移除按钮（保留记账+调试入口）改动最小 → **U3** |
| e | 「训龟大师每一个技能效果和特效需要审核」 | 六个主动技；文案↔数值方向①已有门禁，方向②（代码效果有没有写进文案）**没有** | 审核结论要落成门禁，否则审完还会漂 → §4.3 |
| f | 「地图再度需要提升」 | 地面是**纯色方块无贴图**；装饰带已在 2026-07-23 调稀过（别往密改） | "提升"的方向要用户选 → **U7** |

**没有任何一条需求与代码事实相反**（这次和 2026-07-22 需求3 那次不同）。
唯一被低估的是需求 2：它连带影响 **3 条门禁断言 + 1 个只为暂停存在的中继节点 + 唯一的退出路径**。

---

## 4. 方案

### 4.1 需求1 · 双方总血量 PK 条

#### 版式（推荐 A：中央对撞条 + 两端数字）

```
┌──────────────────────────────────────────────────────────────┐
│ 🐢 我方              [ 上路 1/3 ]              敌方 🐢        │  y=8..16  (标题行·现状)
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                              │
│ ┃████████████████████▌     ░░░░░░░░░░░┃   ← 蓝从左涨/红从右涨 │  y=22..44
│ ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                              │
│  12,480            ▲ 58%                        8,940        │  y=46..60
└──────────────────────────────────────────────────────────────┘
       x=300 ─────────────── 接缝随占比移动 ──────────── x=980
```

- 一条 `680×22` 的条，位于 `x 300..980`、`y 22`（正好落在标题行下方、双路 HUD 之上；
  双路 HUD 要从 `y=44` 下移到 `y=62`，见下方穷举清单第 6 条）
- **蓝（`#3fa9ff`，与左队头像框描边同色）从左往右涨；红（`#ff5a5a`，右队色）从右往左涨。**
  接缝位置 = 左方剩余血 ÷ 双方剩余血之和 —— 这样"谁在赢"一眼可读，不需要读数字
- 两端各一个绝对血量数字（千分位），中间一个百分比 + 箭头（谁占优）
- 血量变化用 `tween` 平滑 `0.25s`（数字用 `tween_method` 滚动），**不要每帧硬跳**——
  群体伤害瞬间会让条抽搐

#### 备选 B：左右分列两条（不推荐，但用户若坚持"左右"字面意思就用它）

```
🐢我方 ████████████▌░░░  12,480          8,940  ░░░████████████ 敌方🐢
x=24..300                                            x=980..1256
```

分列的问题：两条各自归一化到自己的初始血量，**看不出双方相对强弱**，
"PK"的意味就没了（各看各的百分比，要在脑子里做减法）。

#### 数据来源与算法

```gdscript
## 一方的"总血量"= 该侧【计入 PK 的】存活单位当前 hp 之和。
## 分母 = 本路开场时同一集合的 maxHp 之和(★固定不变) —— 不用"当前存活单位 maxHp 之和",
##   否则死一只反而让百分比回升(分母也缩了), 条会往回涨, 完全反直觉。
func _pk_side_hp(side: String) -> Vector2:   # → (当前, 开场总)
```

- **每路重置**：全局时钟 `_t` 跨上路→下路→决胜一直累加（CLAUDE.md §3.4），
  所以基线 `_pk_base_left/right` 必须在**每路开打时**重算，不能只在场景初始化时算一次。
  参照 `_sd_t0` 的写法自己存基线
- **两条伤害路径都要能看到**：`_apply_damage` 与 `_apply_damage_from` 各自扣血（CLAUDE.md §3.3）。
  ★但 PK 条**不在伤害路径里记账**，而是每帧（或每 0.1s）扫 `_units` 求和 —— 这样天然免疫
  「漏改一条路径」和「护盾/回血/复活没走伤害钩」两类漏记
- **禁止拿单位字典做 key / 用 `==` 比较**（CLAUDE.md §3.2）；只读 `u["hp"]`、`u["side"]`、`u.get("alive")`

### 4.2 需求2 · 移除暂停/日志按钮，新增投降

#### 版式

```
右上角(现状)                          右上角(改后)
[📊 1088] [📜 1148] [⏸ 1208]    →    [📊 1148] [🏳 1208]
                                      统计       投降(红底)
```

投降按钮用**红色描边 + 🏳 图标**，与其它 HUD 按钮同尺寸 `52×38`，放在最右 `(1208,12)`
（原暂停位——肌肉记忆上"最右是退出类操作"，且不需要新的安全区计算）。

#### 确认框

```
┌────────────────────────────────┐
│        确认认输？               │
│  投降将直接判定本场失败，       │
│  不可撤销。                     │
│                                 │
│   [ 取消 ]      [ 确认认输 ]    │
│    灰底           红底          │
└────────────────────────────────┘
```

- 半透明遮罩 + 居中面板，遮罩 `mouse_filter = STOP` 吃掉点击（别穿到战场）
- **★弹框期间战斗是否暂停 → U6。** 默认建议：**不暂停**（用户说"不再有暂停"），
  但把弹框 `process_mode = ALWAYS` 以免将来有人加暂停时它跟着卡住
- 「确认认输」走的路径 → **U5**（判本路负 / 判整场负）

#### 穷举清单（改动面 —— 需求 2 一共 11 处，不是 2 处）

| # | 文件:行 | 改什么 |
|---|---|---|
| 1 | [battle_hud.gd:52-59](../../scripts/scenes/battle/battle_hud.gd#L52-L59) | 删 `_pause_btn` 构建 |
| 2 | [battle_hud.gd:63-68](../../scripts/scenes/battle/battle_hud.gd#L63-L68) | 删日志按钮构建（面板与 `_log()` 保留，见 U3） |
| 3 | [battle_hud.gd:72-77](../../scripts/scenes/battle/battle_hud.gd#L72-L77) | 统计按钮 `1088 → 1148`（补上空位） |
| 4 | [battle_hud.gd:47](../../scripts/scenes/battle/battle_hud.gd#L47) | `_build_pause_log_ui()` 改名/改职责为 `_build_topright_btns()` |
| 5 | [battle_hud.gd:194-200](../../scripts/scenes/battle/battle_hud.gd#L194-L200) | 结算时禁用的对象从 `_pause_btn` 换成投降按钮 |
| 6 | [battle_hud.gd:44](../../scripts/scenes/battle/battle_hud.gd#L44) | 双路 HUD `y 44 → 62`（给 PK 条腾位） |
| 7 | [RealtimeBattle3DScene.gd:1155-1163](../../scripts/scenes/RealtimeBattle3DScene.gd#L1155-L1163) | 删 `_pause_panel` 三个按钮（继续/重开/返回菜单） |
| 8 | [RealtimeBattle3DScene.gd:1164-1170](../../scripts/scenes/RealtimeBattle3DScene.gd#L1164-L1170) | 删 `_CamInputRelay`（只为暂停存在）→ **★删前确认 `_unhandled_input` 改动要 F5**（memory `project-god-file-decomposition` 坑 19） |
| 9 | [RealtimeBattle3DScene.gd:1173-1186](../../scripts/scenes/RealtimeBattle3DScene.gd#L1173-L1186) | 删 `_toggle_pause()`；★它里面清 `_pan_active/_pinch_prev` 脏态的逻辑**若别处也依赖，要搬走不能直接删** |
| 10 | [verify_battle_ui.gd:49,108](../../tests/verify_battle_ui.gd#L49) + [verify_ios_ui.gd:282](../../tests/verify_ios_ui.gd#L282) | 三条断言改成"投降按钮已建 / 结算后被禁 / **暂停按钮不存在**"（★反向断言：不许再冒出来） |
| 11 | `verify_cam_pan` / `verify_interaction_matrix` / `verify_debug_arena` | **未验** —— 动手第一步就跑这三个确认是否断言了暂停 |

★调试场（`DEBUG_EDIT`）里的暂停/退出按钮是**开发工具**，不在"局内"范围
（[battle_debug_arena.gd:680](../../scripts/scenes/battle/battle_debug_arena.gd#L680) 有自己的返回菜单）→ **U8**。

### 4.3 需求3 · 训龟大师六技审核

分三步，**每步都要有产物**，不是"看一遍说没问题"：

1. **代码真值清单**（不读文案）——把 `tools/pet_effect_dump.py` 的扫描域从"龟技能分派表"
   扩到 `TRAINER_SKILLS` + `trainer_system.gd`，产出六技的效果清单。
   ★这一步的价值就是无头那次的教训：**分析技能先跑 dump，不读 tooltip**
2. **方向②审计**——`tools/pet_number_audit.py` 现在只跑龟；加一个 trainer 域：
   代码里有的效果（眩晕/减速/受伤加成/复活/衰减/嘲讽…）文案必须提到，
   或登记进 `HIDDEN`。方向①已被 `verify_trainer_desc` 覆盖，不重复做
3. **特效逐技目视**——`DEBUG_EDIT` 调试场摆大师，用 `_edit_trainer_active`
   （[RealtimeBattle3DScene.gd:670](../../scripts/scenes/RealtimeBattle3DScene.gd#L670)）逐个切六技，
   每技截一张。判据不是"有特效"而是 memory `project-vfx-library-rich` 那条：
   **查素材真的显示进了 `_world`，不是只判定生效**

★审核**会不会改数值**取决于审出什么；本方案书**不预设要改**。
若审出数值问题，按 §7 走"先报给用户 → 用户拍板 → 再改"。

### 4.4 需求4 · 地图提升（四条候选路，请用户选，见 U7）

| 路 | 做什么 | 工作量 | 视觉收益 | 风险 |
|---|---|---|---|---|
| **P1 · 地面上纹理**（推荐） | 现在 tile 是**纯色方块**。用 PixelLab `create_topdown_tileset` 生成 grass/water/stone/sand 四套俯视 tile（含边缘过渡），`_tilemap_add` 从收 `Color` 改成收贴图 | 中 | **最大** —— 地面占画面 60%+，从纯色变纹理是质变 | 贴图会拉高 draw call；tile 是 `MultiMesh` 批的，换贴图要按类型分批（现在已是三批，天然适配） |
| **P2 · 补中景** | 远景三层和边框装饰带之间是空的。加一层"中距离"物件：沉船残骸 / 大型珊瑚礁柱 / 断裂石柱，压暗 + 半剪影，摆在 ARENA 外 200~500px 环带 | 中 | 中高 —— 补上纵深断层 | ★**别往边框装饰带里加密度**，2026-07-23 已因"太密"调稀过一轮 |
| **P3 · 用起高低差** | `height` 现在只有 4 档且大面积是 0。加缓坡/台地/中央凹池 | 小 | 中 | ★**历史坑：抬高会让特效掉到地下**（程序化分支注释里写了"不抬高=特效不掉地下"）。要动高度必须先解决特效 y 基准 |
| **P4 · 多张地图轮换** | arena.json 已数据驱动 + 有 `MAPEDIT` 编辑器，加 2~3 张不同布局（窄道 / 双池 / 环形）按赛季或随机选 | 中 | 中 —— 新鲜感而非画质 | 地图形状变了会影响**平衡数据**（正在做第六轮胜率，换图 = 之前六轮数据不可比）→ 建议**排在平衡收官之后** |

**建议顺序：P1 → P2 →（平衡收官后）P4 → P3。**
理由：P1 单位工作量的视觉收益最高且零平衡影响；P3 有明确的历史坑要先填；P4 会污染正在跑的平衡基线。

---

## 5. 已知风险与未决点

### 需用户拍板（U1 U2 U5 不定就动不了手）

| # | 未决点 | 我的建议 | 状态 |
|---|---|---|---|
| **U1** | PK 条的"总血量"**算哪些单位**？龟 / +小将 / +大师 / +龟蛋 | **龟 + 小将 + 大师，不含龟蛋。** 蛋是 atk/def/mr 全 0 的纯血包，算进去会让龟死光了条还是满的。蛋的血单独由现有破蛋 UI 表达 | **未决** |
| **U2** | 版式取**中央对撞条**（方案 A）还是**左右分列两条**（方案 B） | **A**。分列两条各自归一化，看不出相对强弱，"PK"就没了 | **未决** |
| **U5** | 「确认认输」判**本路负**还是**整场负**？ | **整场负**，直接进结算屏（`_settle_season(false)`）。理由：一路一路投降 = 可以刷掉不利路，等于新的策略后门 | **未决** |
| U6 | 确认框弹出时战斗**暂停吗** | **不暂停**（用户说"不再有暂停"）。代价：犹豫期间可能被打死，此时弹框要自动关掉 | **未决** |
| U3 | 日志：只删按钮，还是把 `_log()` 记账系统一起删 | **只删按钮**，`_log()`/面板保留并挂到 `DEBUG_EDIT` 下。理由：`_log()` 被战斗各处调用，`verify_battle_ui` B 组守着它，删了要动的地方多得多，而收益只有"少几行代码" | **未决** |
| U8 | 调试场（`DEBUG_EDIT`）里的暂停/返回按钮要不要一起删 | **不删**。它是开发工具不是"局内"，删了我自己没法排查 | **未决** |
| U7 | 地图走哪几条路、什么顺序 | **P1 → P2 →（平衡收官后）P4 → P3** | **未决** |
| U9 | 大师审核**是否允许顺手改数值** | **不允许**——先出审核报告，用户拍板再改。理由：审核和平衡是两件事，混在一起就说不清哪个改动导致胜率变化 | **未决** |

### 已知风险（不需拍板，但必须堵）

| 风险 | 为什么会出事 | 怎么堵 |
|---|---|---|
| **R1 · 需求2 会打红 3 条门禁** | `verify_battle_ui:49/108`、`verify_ios_ui:282` 断言 `_pause_btn != null` | 同一提交里把三条改成**反向断言**（"暂停按钮不存在"），不是删掉断言。删掉 = 以后有人加回来也没人知道 |
| **R2 · `_CamInputRelay` 是暂停的伴生物** | 它 `PROCESS_MODE_ALWAYS`，只为"暂停时还能拖镜头"存在 | 删它同时要跑 `verify_cam_pan` 确认非暂停下的拖镜头没被连坐；★动 `_unhandled_input` 相关的要 F5 真机验（memory 坑 19） |
| **R3 · `_toggle_pause` 里清脏态的逻辑可能别处也需要** | 它清 `_pan_active/_pan_moved/_touch_pts/_pinch_prev` —— 这是"拖动中途被打断"的通用修复，不只暂停会打断 | 删函数前先 grep 这四个字段的所有写入点；若投降弹框也算"打断"，把这段搬进一个 `_clear_input_dirty()` |
| **R4 · PK 条分母用"当前存活 maxHp 之和"会反向涨** | 死一只则分子分母同缩，百分比可能回升 | 分母固定为**本路开场基线**，且**每路重算**（`_t` 跨路累加，CLAUDE.md §3.4） |
| **R5 · 每帧扫 `_units` 求和的开销** | 主文件是每帧耦合的核心 sim 循环，热路径边界预算 <0.2%（memory 拆分战役） | 降到 **每 0.1s 采样一次**（UI 平滑靠 tween 补），并**先测背对背基线**（memory 坑 17：热降频毁冷基线，要用 stash 背对背比） |
| **R6 · 投降按钮误触** | 它在原暂停位，手机横屏右上角正好是拇指扫过区 | 确认框是必需的（需求已含）；另外按钮不做长按快捷、不做手势 |
| **R7 · P1 换贴图拉高 draw call** | tile 是 `MultiMesh` 批渲染 | 按 tile 类型分批（现已三批），一类一张图集；改完跑 `verify_map_geometry` + 看帧时间 |
| **R8 · P4 换地图污染平衡基线** | 第六轮胜率刚跑完，换图形状 = 六轮数据全不可比 | P4 排到平衡收官后 |
| **R9 · 大师审核可能审出"文案没写的效果"** | 无头那次就是（镰刀横扫整段没写） | 审核的产物必须是**双向**的：不只查数值对不对，还要查代码效果文案有没有提 |

### 未验（动手第一步就要验）

- **V1**：`verify_cam_pan` / `verify_interaction_matrix` / `verify_debug_arena` 里的 pause 引用**是不是断言按钮存在**（§2.3 表格最后一行）
- **V2**：投降走 `_settle_season(false)` 在**双路流程中途**（上路刚打完、下路还没开）调用会不会出错
- **V3**：PK 条每 0.1s 扫全场的实际帧开销（背对背 stash 测）
- **V4**：`_tilemap_add` 换成贴图后，`MultiMesh` 是否还能保持三批（P1 的前提）

---

## 6. 验收标准（以及怎么证明这个检查会 FAIL）

新建 `tests/verify_battle_hud_r1.gd`（需求1+2）、扩 `tools/pet_number_audit.py`（需求3）。
**每条都要配一次反向验证 —— 故意改坏，确认真的红。**

| 需求 | 判据 | 反向验证（怎么证明会 FAIL） |
|---|---|---|
| 1 | PK 条节点已建；左右两半的填充宽度之和 == 条总宽（接缝无缝隙） | 把某一半的宽度算式 `×0.9` → 必须红 |
| 1 | 分母 = 开场基线且**每路重算** | 在第二路开打后断言基线 != 第一路的值；把"每路重算"那行注掉 → 必须红 |
| 1 | 龟蛋**不计入**（U1 若采纳建议） | 造一个含蛋的合成场景，蛋满血 / 龟全死 → 条必须为 0；把蛋加回求和 → 必须红 |
| 1 | 用**干净合成单位**测精确数值 | memory `fb-ci-vs-local-divergence`：随机 spawn 单位会因队伍未播种 RNG / 敌带盾而 CI 偶发红 |
| 2 | `_pause_btn` **字段不存在**（反向断言） | 把 `_pause_btn` 加回来 → 必须红 |
| 2 | 日志按钮不在 `_ui_layer` 的子节点里 | 加回按钮 → 必须红 |
| 2 | 投降按钮已建 + 结算后 `disabled` | 删掉 `disabled = true` 那行 → 必须红 |
| 2 | 确认框：点「取消」不结算、点「确认」进结算屏 | 把「取消」也接到结算 → 必须红 |
| 3 | 六技**全部**被方向②审计覆盖（★打印分母：`N=6`，`N=0` 是空检查不是通过） | 从某技的 desc 里删掉一个效果关键词 → 必须报"文案未提且未登记" |
| 3 | 每技特效**真的进了 `_world`**（不是只判定生效） | 把某技的特效 `add_child` 注掉 → 必须红 |
| 4 (P1) | 四类 tile 各自拿到贴图；`verify_map_geometry` 仍绿 | 把某类的贴图置 null → 必须红 |
| 全部 | `bash run-tests.sh` 全绿（**不是只跑 `sweep.sh`** —— CLAUDE.md §2 那条：审计器不在 sweep 里） | — |
| 全部 | 本地绿 ≠ CI 绿，push 后用 Actions API 亲自看 conclusion | — |

版本号：需求 1、2、4 玩家可感知 → 各自升第 3 位（`0.17.7` / `0.17.8` / …），
四处同改 + CHANGELOG + git tag。需求 3 若只出报告不改数值，**不升版本**（开发工作不升，同调试场先例）。

---

## 7. 决策记录

| 时间 | 谁 | 内容 |
|---|---|---|
| 2026-07-30 | 用户 | 提出四条新需求；明确需求 1「需要详细设计下」、需求 2「需要设计一下」；「等确认没问题就搞新的方案书」 |
| 2026-07-30 | 我 | 先把第六轮平衡收口（r6 门禁 41 条 + 版本 0.17.6 + 全套门禁），再出本方案书 |
| 2026-07-30 | 我 | 建议 U1 不含龟蛋、U2 取中央对撞条、U5 投降判整场负、U3 只删按钮保留 `_log()`、U7 走 P1→P2→P4→P3 |
| 2026-07-30 | 我 | 指出需求 2 的真实改动面是 **11 处**（含 3 条会打红的门禁断言 + 1 个只为暂停存在的中继节点 + 唯一退出路径的消失），不是字面上的"删两个按钮" |
| 2026-07-30 | 我 | 需求 3 的缺口是**方向②**（代码效果 → 文案有没有提），方向①已由 `verify_trainer_desc` 覆盖；不预设要改数值（U9） |
| 待 | 用户 | U1 ~ U9 |

---

## 8. 实施后回填

（留空 —— 实际改了哪些、和方案的偏差、新发现的坑）
